CREATE TABLE "app_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"timezone" text,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "coach_calls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coach_calls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ts" text NOT NULL,
	"endpoint" text NOT NULL,
	"goal_id" integer,
	"tokens_in" integer DEFAULT 0 NOT NULL,
	"tokens_out" integer DEFAULT 0 NOT NULL,
	"duration_ms" integer DEFAULT 0 NOT NULL,
	"model" text NOT NULL,
	"status" text DEFAULT 'success' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_summaries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_summaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"metric_type_id" integer NOT NULL,
	"avg_value" double precision,
	"min_value" double precision,
	"max_value" double precision,
	"count" integer DEFAULT 0 NOT NULL,
	"last_ingest_at" text
);
--> statement-breakpoint
CREATE TABLE "dashboard_widgets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboard_widgets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dashboard_id" integer NOT NULL,
	"widget_type" text NOT NULL,
	"config" text DEFAULT '{}' NOT NULL,
	"body" text,
	"grid_x" integer DEFAULT 0 NOT NULL,
	"grid_y" integer DEFAULT 0 NOT NULL,
	"grid_w" integer DEFAULT 12 NOT NULL,
	"grid_h" integer DEFAULT 2 NOT NULL,
	"position" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dashboards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dashboards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"icon" text,
	"sport_id" integer,
	"position" integer DEFAULT 0 NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"seeded_id" text,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL,
	CONSTRAINT "dashboards_slug_unique" UNIQUE("slug"),
	CONSTRAINT "dashboards_seeded_id_unique" UNIQUE("seeded_id")
);
--> statement-breakpoint
CREATE TABLE "event_metrics" (
	"event_id" integer NOT NULL,
	"metric_type_id" integer NOT NULL,
	"value" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sport_id" integer NOT NULL,
	"type" text NOT NULL,
	"duration_minutes" integer,
	"notes" text,
	"started_at" text NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"source_id" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "focuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "focuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"goal_id" integer NOT NULL,
	"source" text DEFAULT 'manual' NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text,
	"status" text DEFAULT 'active' NOT NULL,
	"technical_notes" text,
	"evidence" text,
	"dismissed_at" text,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "goal_journal_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goal_journal_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"goal_id" integer NOT NULL,
	"content" text NOT NULL,
	"created_at" text NOT NULL,
	"verdict_focus_id" integer,
	"linked_metric_type_id" integer
);
--> statement-breakpoint
CREATE TABLE "goals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"metric_type_id" integer NOT NULL,
	"sport_id" integer NOT NULL,
	"target_value" double precision NOT NULL,
	"deadline" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "import_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "import_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"mapping" text NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "import_sources_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "ingest_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ingest_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"api_key_encrypted" text,
	"last_sync_at" text,
	"enabled" boolean DEFAULT true NOT NULL,
	CONSTRAINT "ingest_configs_source_unique" UNIQUE("source")
);
--> statement-breakpoint
CREATE TABLE "merge_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "merge_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"created_at" text NOT NULL,
	"canonical_id" integer NOT NULL,
	"canonical_name" text NOT NULL,
	"merged_names" text NOT NULL,
	"payload" text NOT NULL,
	"undone_at" text,
	"user_id" integer
);
--> statement-breakpoint
CREATE TABLE "metric_type_aliases" (
	"alias" text PRIMARY KEY NOT NULL,
	"canonical_metric_type_id" integer NOT NULL,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "metric_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "metric_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"sport_id" integer,
	"unit" text NOT NULL,
	"frequency_hint" text DEFAULT 'daily' NOT NULL,
	"target" double precision,
	"higher_is_better" boolean DEFAULT true NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "metric_types_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "metrics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "metrics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"metric_type_id" integer NOT NULL,
	"value" double precision NOT NULL,
	"recorded_at" text NOT NULL,
	"source" text NOT NULL,
	"source_id" text,
	"created_at" text NOT NULL,
	"alias" text
);
--> statement-breakpoint
CREATE TABLE "reconcile_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconcile_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" text NOT NULL,
	"kind" text NOT NULL,
	"metric_type_id" integer,
	"deleted_count" integer NOT NULL,
	"range_start" text NOT NULL,
	"range_end" text NOT NULL,
	"at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "source_settings" (
	"source" text PRIMARY KEY NOT NULL,
	"reconcile_enabled" boolean DEFAULT false NOT NULL,
	"updated_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"color" text NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "sports_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "workout_sets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workout_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"exercise_metric_type_id" integer NOT NULL,
	"set_number" integer NOT NULL,
	"reps" integer NOT NULL,
	"weight" double precision NOT NULL,
	"rpe" double precision,
	"notes" text
);
--> statement-breakpoint
ALTER TABLE "coach_calls" ADD CONSTRAINT "coach_calls_goal_id_goals_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_summaries" ADD CONSTRAINT "daily_summaries_metric_type_id_metric_types_id_fk" FOREIGN KEY ("metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_widgets" ADD CONSTRAINT "dashboard_widgets_dashboard_id_dashboards_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."dashboards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboards" ADD CONSTRAINT "dashboards_sport_id_sports_id_fk" FOREIGN KEY ("sport_id") REFERENCES "public"."sports"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_metrics" ADD CONSTRAINT "event_metrics_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_metrics" ADD CONSTRAINT "event_metrics_metric_type_id_metric_types_id_fk" FOREIGN KEY ("metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_sport_id_sports_id_fk" FOREIGN KEY ("sport_id") REFERENCES "public"."sports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "focuses" ADD CONSTRAINT "focuses_goal_id_goals_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_journal_entries" ADD CONSTRAINT "goal_journal_entries_goal_id_goals_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_journal_entries" ADD CONSTRAINT "goal_journal_entries_verdict_focus_id_focuses_id_fk" FOREIGN KEY ("verdict_focus_id") REFERENCES "public"."focuses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_journal_entries" ADD CONSTRAINT "goal_journal_entries_linked_metric_type_id_metric_types_id_fk" FOREIGN KEY ("linked_metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_metric_type_id_metric_types_id_fk" FOREIGN KEY ("metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_sport_id_sports_id_fk" FOREIGN KEY ("sport_id") REFERENCES "public"."sports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metric_type_aliases" ADD CONSTRAINT "metric_type_aliases_canonical_metric_type_id_metric_types_id_fk" FOREIGN KEY ("canonical_metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metric_types" ADD CONSTRAINT "metric_types_sport_id_sports_id_fk" FOREIGN KEY ("sport_id") REFERENCES "public"."sports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "metrics" ADD CONSTRAINT "metrics_metric_type_id_metric_types_id_fk" FOREIGN KEY ("metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workout_sets" ADD CONSTRAINT "workout_sets_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workout_sets" ADD CONSTRAINT "workout_sets_exercise_metric_type_id_metric_types_id_fk" FOREIGN KEY ("exercise_metric_type_id") REFERENCES "public"."metric_types"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_coach_calls_ts" ON "coach_calls" USING btree ("ts");--> statement-breakpoint
CREATE INDEX "idx_coach_calls_goal" ON "coach_calls" USING btree ("goal_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_daily_summaries_date_metric" ON "daily_summaries" USING btree ("date","metric_type_id");--> statement-breakpoint
CREATE INDEX "idx_dashboard_widgets_dashboard_position" ON "dashboard_widgets" USING btree ("dashboard_id","position");--> statement-breakpoint
CREATE INDEX "idx_dashboards_position" ON "dashboards" USING btree ("position");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_event_metrics_event_type" ON "event_metrics" USING btree ("event_id","metric_type_id");--> statement-breakpoint
CREATE INDEX "idx_events_sport_started" ON "events" USING btree ("sport_id","started_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_events_source_id" ON "events" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "idx_focuses_goal_status" ON "focuses" USING btree ("goal_id","status");--> statement-breakpoint
CREATE INDEX "idx_goal_journal_goal_created" ON "goal_journal_entries" USING btree ("goal_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_merge_log_created_at" ON "merge_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_merge_log_user_id_created_at" ON "merge_log" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_metric_type_aliases_canonical" ON "metric_type_aliases" USING btree ("canonical_metric_type_id");--> statement-breakpoint
CREATE INDEX "idx_metrics_type_recorded" ON "metrics" USING btree ("metric_type_id","recorded_at");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_metrics_source_id" ON "metrics" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX "idx_metrics_type_alias" ON "metrics" USING btree ("metric_type_id","alias");--> statement-breakpoint
CREATE INDEX "idx_reconcile_log_source_at" ON "reconcile_log" USING btree ("source","at");--> statement-breakpoint
CREATE INDEX "idx_workout_sets_event" ON "workout_sets" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "idx_workout_sets_exercise_mt" ON "workout_sets" USING btree ("exercise_metric_type_id");