-- Multi-user (PR 2). Adds Auth.js + Delta-extension tables, threads
-- user_id through every OWNED table, swaps singleton-style uniques for
-- per-user composite uniques, and rewires ingest_configs for the
-- per-user encrypted-secret model.
--
-- All existing rows belong to user_id=1 (the bootstrap owner). Every
-- ALTER TABLE that adds user_id uses DEFAULT 1 so backfill is implicit
-- under the NOT NULL constraint. We don't drop the default in this
-- migration — it's a development-time convenience, removed in a
-- follow-up after every code-path explicitly threads user.id from
-- requireUser(). Until then the default catches any forgotten caller
-- and routes the row to the owner instead of erroring at insert time.

-- ============================================================================
-- 1. Auth.js base tables (users + Delta extensions, accounts, sessions,
--    verification_tokens). Integer ids match the rest of Delta's schema.
-- ============================================================================

CREATE TABLE "users" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 CACHE 1),
    "name" text,
    "email" text,
    "email_verified" timestamp,
    "image" text,
    "display_name" text NOT NULL,
    "password_hash" text,
    "password_hash_version" integer DEFAULT 1 NOT NULL,
    "is_owner" boolean DEFAULT false NOT NULL,
    "created_at" text NOT NULL,
    CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint

CREATE TABLE "accounts" (
    "user_id" integer NOT NULL,
    "type" text NOT NULL,
    "provider" text NOT NULL,
    "provider_account_id" text NOT NULL,
    "refresh_token" text,
    "access_token" text,
    "expires_at" integer,
    "token_type" text,
    "scope" text,
    "id_token" text,
    "session_state" text,
    CONSTRAINT "accounts_provider_provider_account_id_pk" PRIMARY KEY("provider", "provider_account_id"),
    CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint

CREATE TABLE "sessions" (
    "session_token" text PRIMARY KEY NOT NULL,
    "user_id" integer NOT NULL,
    "expires" timestamp NOT NULL,
    CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint

CREATE TABLE "verification_tokens" (
    "identifier" text NOT NULL,
    "token" text NOT NULL,
    "expires" timestamp NOT NULL,
    CONSTRAINT "verification_tokens_identifier_token_pk" PRIMARY KEY("identifier", "token")
);
--> statement-breakpoint

-- ============================================================================
-- 2. Custom auth-support tables.
-- ============================================================================

CREATE TABLE "invite_codes" (
    "code" text PRIMARY KEY NOT NULL,
    "created_by_user_id" integer NOT NULL,
    "used_by_user_id" integer,
    "expires_at" text,
    "used_at" text,
    "created_at" text NOT NULL,
    CONSTRAINT "invite_codes_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action,
    CONSTRAINT "invite_codes_used_by_user_id_users_id_fk" FOREIGN KEY ("used_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action
);
--> statement-breakpoint

CREATE TABLE "oauth_states" (
    "state" text PRIMARY KEY NOT NULL,
    "user_id" integer NOT NULL,
    "expires_at" text NOT NULL,
    CONSTRAINT "oauth_states_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint

CREATE TABLE "session_denylist" (
    "jti" text PRIMARY KEY NOT NULL,
    "user_id" integer NOT NULL,
    "revoked_at" text NOT NULL,
    CONSTRAINT "session_denylist_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint

CREATE TABLE "dashboard_share_tokens" (
    "token" text PRIMARY KEY NOT NULL,
    "dashboard_id" integer NOT NULL,
    "created_by_user_id" integer NOT NULL,
    "created_at" text NOT NULL,
    "revoked_at" text,
    CONSTRAINT "dashboard_share_tokens_dashboard_id_dashboards_id_fk" FOREIGN KEY ("dashboard_id") REFERENCES "public"."dashboards"("id") ON DELETE cascade ON UPDATE no action,
    CONSTRAINT "dashboard_share_tokens_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint

CREATE UNIQUE INDEX "dashboard_share_tokens_one_active_per_dashboard"
  ON "dashboard_share_tokens" ("dashboard_id")
  WHERE "revoked_at" IS NULL;
--> statement-breakpoint

-- ============================================================================
-- 3. Bootstrap owner row. Pinned at id=1 so every OWNED table's
--    user_id DEFAULT 1 backfills cleanly. password_hash='!' is the
--    "un-bootstrapped" sentinel that authorize() rejects with the
--    same generic error as a wrong password.
--    OVERRIDING SYSTEM VALUE because the id column is GENERATED BY
--    DEFAULT AS IDENTITY — explicit ids need the override.
-- ============================================================================

INSERT INTO "users" ("id", "display_name", "password_hash", "is_owner", "created_at")
OVERRIDING SYSTEM VALUE
VALUES (1, 'Owner', '!', true, '2026-01-01T00:00:00.000Z');
--> statement-breakpoint

-- Bump the sequence past 1 so the next inserted user gets id=2.
SELECT setval('users_id_seq', 1);
--> statement-breakpoint

-- ============================================================================
-- 4. user_id column on every OWNED table. DEFAULT 1 backfills any
--    existing rows to the owner, and stays as a development-time
--    safety net.
-- ============================================================================

ALTER TABLE "sports" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "metric_types" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "metric_type_aliases" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "metrics" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "goals" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "ingest_configs" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "import_sources" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
-- merge_log.user_id already exists (nullable) from the merge-undo work
-- in 0000_initial_schema. Backfill nulls to 1, flip to NOT NULL, add
-- the FK that didn't exist pre-multi-user.
UPDATE "merge_log" SET "user_id" = 1 WHERE "user_id" IS NULL;--> statement-breakpoint
ALTER TABLE "merge_log" ALTER COLUMN "user_id" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "merge_log" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "merge_log" ADD CONSTRAINT "merge_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "reconcile_log" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "daily_summaries" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "dashboards" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint

-- coach_calls: user_id is NULLABLE (set to NULL on user delete to keep
-- cost-attribution history alive). Add deleted_user_hash for
-- per-ex-user bucketing without retaining the email.
ALTER TABLE "coach_calls" ADD COLUMN "user_id" integer DEFAULT 1 REFERENCES "users"("id") ON DELETE set null;--> statement-breakpoint
ALTER TABLE "coach_calls" ADD COLUMN "deleted_user_hash" text;--> statement-breakpoint
CREATE INDEX "idx_coach_calls_user" ON "coach_calls" ("user_id");--> statement-breakpoint

-- ============================================================================
-- 5. app_settings: drop the singleton id column, make user_id PK.
--    Pre-migration there's exactly one row with id=1; we already added
--    user_id with DEFAULT 1, so dropping id is safe.
-- ============================================================================

ALTER TABLE "app_settings" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "app_settings" DROP CONSTRAINT IF EXISTS "app_settings_pkey";--> statement-breakpoint
ALTER TABLE "app_settings" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "app_settings" ADD CONSTRAINT "app_settings_pkey" PRIMARY KEY ("user_id");--> statement-breakpoint

-- ============================================================================
-- 6. source_settings: PK becomes (user_id, source).
-- ============================================================================

ALTER TABLE "source_settings" ADD COLUMN "user_id" integer DEFAULT 1 NOT NULL REFERENCES "users"("id") ON DELETE cascade;--> statement-breakpoint
ALTER TABLE "source_settings" DROP CONSTRAINT IF EXISTS "source_settings_pkey";--> statement-breakpoint
ALTER TABLE "source_settings" ADD CONSTRAINT "source_settings_pkey" PRIMARY KEY ("user_id", "source");--> statement-breakpoint

-- ============================================================================
-- 7. metric_type_aliases: PK from (alias) to (user_id, alias). Existing
--    rows already have user_id=1 from the ADD COLUMN above.
-- ============================================================================

ALTER TABLE "metric_type_aliases" DROP CONSTRAINT IF EXISTS "metric_type_aliases_pkey";--> statement-breakpoint
ALTER TABLE "metric_type_aliases" ADD CONSTRAINT "metric_type_aliases_pkey" PRIMARY KEY ("user_id", "alias");--> statement-breakpoint

-- ============================================================================
-- 8. Drop old single-column UNIQUE constraints; add composite (user_id, X)
--    indexes. Do drops BEFORE adds so two passes against the same name
--    don't conflict.
-- ============================================================================

ALTER TABLE "sports" DROP CONSTRAINT IF EXISTS "sports_name_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "sports_user_name_uniq" ON "sports" ("user_id", "name");--> statement-breakpoint

ALTER TABLE "metric_types" DROP CONSTRAINT IF EXISTS "metric_types_name_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "metric_types_user_name_uniq" ON "metric_types" ("user_id", "name");--> statement-breakpoint

ALTER TABLE "import_sources" DROP CONSTRAINT IF EXISTS "import_sources_name_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "import_sources_user_name_uniq" ON "import_sources" ("user_id", "name");--> statement-breakpoint

ALTER TABLE "dashboards" DROP CONSTRAINT IF EXISTS "dashboards_slug_unique";--> statement-breakpoint
ALTER TABLE "dashboards" DROP CONSTRAINT IF EXISTS "dashboards_seeded_id_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "dashboards_user_slug_uniq" ON "dashboards" ("user_id", "slug");--> statement-breakpoint
CREATE UNIQUE INDEX "dashboards_user_seeded_id_uniq" ON "dashboards" ("user_id", "seeded_id");--> statement-breakpoint

ALTER TABLE "ingest_configs" DROP CONSTRAINT IF EXISTS "ingest_configs_source_unique";--> statement-breakpoint
CREATE UNIQUE INDEX "ingest_configs_user_source_uniq" ON "ingest_configs" ("user_id", "source");--> statement-breakpoint

-- metrics + events: source_id was a single-column UNIQUE INDEX (not a
-- constraint), drop and recreate as composite.
DROP INDEX IF EXISTS "idx_metrics_source_id";--> statement-breakpoint
CREATE UNIQUE INDEX "idx_metrics_user_source_id" ON "metrics" ("user_id", "source_id");--> statement-breakpoint
CREATE INDEX "idx_metrics_user" ON "metrics" ("user_id");--> statement-breakpoint

DROP INDEX IF EXISTS "idx_events_source_id";--> statement-breakpoint
CREATE UNIQUE INDEX "idx_events_user_source_id" ON "events" ("user_id", "source_id");--> statement-breakpoint
CREATE INDEX "idx_events_user" ON "events" ("user_id");--> statement-breakpoint

DROP INDEX IF EXISTS "idx_daily_summaries_date_metric";--> statement-breakpoint
CREATE UNIQUE INDEX "idx_daily_summaries_user_date_metric" ON "daily_summaries" ("user_id", "date", "metric_type_id");--> statement-breakpoint

CREATE INDEX "idx_reconcile_log_user" ON "reconcile_log" ("user_id");--> statement-breakpoint

-- ============================================================================
-- 9. ingest_configs: rename api_key_encrypted -> encrypted_value (still
--    text), add lookup_hash for HAE bearer-token sha256 lookup.
-- ============================================================================

ALTER TABLE "ingest_configs" RENAME COLUMN "api_key_encrypted" TO "encrypted_value";--> statement-breakpoint
ALTER TABLE "ingest_configs" ADD COLUMN "lookup_hash" text;--> statement-breakpoint
CREATE INDEX "idx_ingest_configs_lookup_hash" ON "ingest_configs" ("lookup_hash");
