-- Composite-event scaffolding for #4.
--
-- `events.status` flags an event as a normal record ('visible'), a
-- member that's been folded into a composite ('hidden_by_composite'),
-- or the composite itself ('composite'). Default 'visible' preserves
-- the existing semantics for every legacy row.
--
-- `events.composite_member_ids` is non-empty only for composite rows;
-- it lists the event ids that were merged together. Children
-- (event_metrics, workout_sets) stay attached to the member rows;
-- composite renders join via WHERE event_id = ANY(composite_member_ids).
--
-- `event_duplicate_denylist` is the dismiss-once-forever memory. When a
-- user clicks "Not a duplicate" on a candidate pair, or unmerges a
-- composite, the (event_a_id, event_b_id) tuple lands here. The
-- duplicate detector skips any pair in this table. Always insert with
-- event_a_id < event_b_id so the lookup is symmetric.

ALTER TABLE events ADD COLUMN status text NOT NULL DEFAULT 'visible';
ALTER TABLE events ADD COLUMN composite_member_ids integer[] NOT NULL DEFAULT '{}';

CREATE TABLE event_duplicate_denylist (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_a_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  event_b_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  created_at text NOT NULL,
  CONSTRAINT event_duplicate_denylist_ordered CHECK (event_a_id < event_b_id),
  UNIQUE (event_a_id, event_b_id)
);
CREATE INDEX idx_event_duplicate_denylist_user ON event_duplicate_denylist (user_id);
