-- Journal entries on events (issue #19).
--
-- Free-form notes attached to any event (regular or composite),
-- mirroring goal_journal_entries but keyed on events.id. INHERIT —
-- no user_id of its own; scoped through events.user_id in queries.
--
-- Both timestamps are timestamptz (the isoTimestamptz custom column
-- type, per #25). updated_at is set on create and on every PATCH.

CREATE TABLE event_journal_entries (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
--> statement-breakpoint
CREATE INDEX idx_event_journal_event_created
  ON event_journal_entries (event_id, created_at DESC);
